# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/blaze/User Experience — First Look/Mirror shader"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/blaze/User Experience — First Look/Mirror shader"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/blaze/User Experience — First Look/Mirror shader/CMakeFiles" "/home/blaze/User Experience — First Look/Mirror shader/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/blaze/User Experience — First Look/Mirror shader/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shadersandbox

# Build rule for target.
shadersandbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shadersandbox
.PHONY : shadersandbox

# fast build rule for target.
shadersandbox/fast:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/build
.PHONY : shadersandbox/fast

demo.o: demo.cc.o

.PHONY : demo.o

# target to build an object file
demo.cc.o:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/demo.cc.o
.PHONY : demo.cc.o

demo.i: demo.cc.i

.PHONY : demo.i

# target to preprocess a source file
demo.cc.i:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/demo.cc.i
.PHONY : demo.cc.i

demo.s: demo.cc.s

.PHONY : demo.s

# target to generate assembly for a file
demo.cc.s:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/demo.cc.s
.PHONY : demo.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/main.cc.s
.PHONY : main.cc.s

shader.o: shader.cc.o

.PHONY : shader.o

# target to build an object file
shader.cc.o:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/shader.cc.o
.PHONY : shader.cc.o

shader.i: shader.cc.i

.PHONY : shader.i

# target to preprocess a source file
shader.cc.i:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/shader.cc.i
.PHONY : shader.cc.i

shader.s: shader.cc.s

.PHONY : shader.s

# target to generate assembly for a file
shader.cc.s:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/shader.cc.s
.PHONY : shader.cc.s

third_party/stb_image/stb_image.o: third_party/stb_image/stb_image.c.o

.PHONY : third_party/stb_image/stb_image.o

# target to build an object file
third_party/stb_image/stb_image.c.o:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/third_party/stb_image/stb_image.c.o
.PHONY : third_party/stb_image/stb_image.c.o

third_party/stb_image/stb_image.i: third_party/stb_image/stb_image.c.i

.PHONY : third_party/stb_image/stb_image.i

# target to preprocess a source file
third_party/stb_image/stb_image.c.i:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/third_party/stb_image/stb_image.c.i
.PHONY : third_party/stb_image/stb_image.c.i

third_party/stb_image/stb_image.s: third_party/stb_image/stb_image.c.s

.PHONY : third_party/stb_image/stb_image.s

# target to generate assembly for a file
third_party/stb_image/stb_image.c.s:
	$(MAKE) -f CMakeFiles/shadersandbox.dir/build.make CMakeFiles/shadersandbox.dir/third_party/stb_image/stb_image.c.s
.PHONY : third_party/stb_image/stb_image.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... shadersandbox"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... third_party/stb_image/stb_image.o"
	@echo "... third_party/stb_image/stb_image.i"
	@echo "... third_party/stb_image/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

